Mecanum drive
5152Alotobots/2023robotCode pull request #18
Opened 2023-01-27 17:59 UTC by Rkortlandt

Add Mecanum Drive

2023-01-27 18:12 UTC, SeanErn requested changes

2023-01-27 18:12 UTC, SeanErn commented on src/main/java/frc/robot/ChargedUp/MecanumDrive/Subsys_MecanumDrive.java
> +  /*** Initializes Shuffleboard motor objects */
Remove this PLEASE

2023-01-27 18:12 UTC, SeanErn commented on src/main/java/frc/robot/RobotContainer.java
> -  // The robot's subsystems and commands are defined here...
Do we need these comments @chrisdeboer?

2023-01-27 18:15 UTC, SeanErn approved these changes
Good job

2023-01-28 02:08 UTC, SeanErn commented
still need fix

2023-01-28 02:16 UTC, SeanErn commented
No both S capitals

2023-01-28 02:28 UTC, SeanErn requested changes

2023-01-28 02:28 UTC, SeanErn commented on src/main/java/frc/robot/ChargedUp/MecanumDrive/SubSys_MecanumDrive.java
> +    m_rearRightMotor.setInverted(false);
Why is this here? It isn't inverted by default

2023-01-28 14:25 UTC, chrisdeboer approved these changes

2023-01-28 14:27 UTC, chrisdeboer approved these changes

2023-01-28 14:28 UTC, chrisdeboer commented on src/main/java/frc/robot/ChargedUp/MecanumDrive/SubSys_MecanumDrive.java
> +    m_rearRightMotor.setInverted(false);
It's okay for now

2023-01-28 14:28 UTC, chrisdeboer approved these changes

2023-01-28 14:30 UTC, SeanErn approved these changes

2023-01-28 14:30 UTC, merged