Merge swerve code & dev auto balance
5152Alotobots/2023robotCode pull request #20
Opened 2023-01-29 23:33 UTC by SeanErn

2023-01-29 23:54 UTC, SeanErn reviewed
Looks good, but don't approve  it until I can test it on BOTH robots

2023-01-30 12:30 UTC, Rkortlandt requested changes
Good over all just some formatting things in the new command. It would be helpful if we moved the old drive code to the bottom.

2023-01-30 12:30 UTC, Rkortlandt commented on src/main/java/frc/robot/ChargedUp/ChargeStation/Cmd_AutoBalance.java
> +    if (pitch > 8 || pitch < -8) {
Remove useless comment explaining the if statement replace 8 & -8 with constants like maxPitch and minPitch

2023-01-30 12:30 UTC, Rkortlandt commented on src/main/java/frc/robot/ChargedUp/ChargeStation/Cmd_AutoBalance.java
> +    } else if (roll > 8 || roll < -8) { // If roll is greater than 8 or less than -8...
Remove useless comment. Replace 8 & -8 with constants.

2023-01-30 12:30 UTC, Rkortlandt commented on src/main/java/frc/robot/RobotContainer.java
> +      */
Move to bottom or somewhere out of the way

2023-01-30 12:30 UTC, Rkortlandt commented on src/main/java/frc/robot/RobotContainer.java
This too

2023-01-30 14:09 UTC, SeanErn commented on src/main/java/frc/robot/RobotContainer.java
> +      */
I don't know if it works yet so I just left it there.

2023-01-30 14:10 UTC, SeanErn commented on src/main/java/frc/robot/ChargedUp/ChargeStation/Cmd_AutoBalance.java
> +    if (pitch > 8 || pitch < -8) {
Fixed with new commit

2023-01-30 14:19 UTC, SeanErn commented on src/main/java/frc/robot/RobotContainer.java
I don't know if it works yet

2023-01-30 14:48 UTC, Rkortlandt commented on src/main/java/frc/robot/RobotContainer.java
> +      */
ok

2023-01-30 14:49 UTC, Rkortlandt approved these changes

2023-01-30 16:27 UTC, Rkortlandt commented on src/main/java/frc/robot/ChargedUp/ChargeStation/Cmd_AutoBalance.java
> +    double roll = m_PigeonGyro.getRawGyroRoll();
Is this comment really necessary?

2023-01-30 22:40 UTC, SeanErn commented on src/main/java/frc/robot/ChargedUp/ChargeStation/Cmd_AutoBalance.java
> +    double roll = m_PigeonGyro.getRawGyroRoll();
fixed

2023-02-03 00:04 UTC, SeanErn commented
Waiting for path planner code

2024-03-01 17:11 UTC, closed without merging